[package]
name = "lumious_headless_helper"
version.workspace = true
edition = "2024"

[dependencies]
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
signal-hook = "0.4.1"
stream_message.workspace = true
